import tempfile
import webbrowser
import os


def _fmt_time(seconds):
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    if h > 0:
        return f"{h}h {m:02d}m {s:02d}s"
    return f"{m}m {s:02d}s"


def _group_zones(segments):
    if not segments:
        return []

    groups = []
    current_zone = segments[0]['zone_label']
    current_start = 0

    for i, seg in enumerate(segments):
        if seg['zone_label'] != current_zone:
            groups.append((current_start, i - 1, current_zone))
            current_zone = seg['zone_label']
            current_start = i

    groups.append((current_start, len(segments) - 1, current_zone))

    merged = []
    for start, end, zone in groups:
        zone_segs = segments[start:end + 1]
        total_dist = sum(s['distance_m'] for s in zone_segs)
        avg_power = sum(s['power_w'] * s['time_s'] for s in zone_segs) / max(1, sum(s['time_s'] for s in zone_segs))
        avg_speed = sum(s['speed_ms'] * s['time_s'] for s in zone_segs) / max(1, sum(s['time_s'] for s in zone_segs))
        total_time = sum(s['time_s'] for s in zone_segs)
        avg_gradient = sum(s['gradient'] * s['distance_m'] for s in zone_segs) / max(1, total_dist)

        merged.append({
            'zone': zone,
            'start_km': zone_segs[0]['cumulative_m'] / 1000,
            'end_km': (zone_segs[-1]['cumulative_m'] + zone_segs[-1]['distance_m']) / 1000,
            'distance_km': total_dist / 1000,
            'avg_gradient': avg_gradient,
            'avg_power': avg_power,
            'avg_speed_kmh': avg_speed * 3.6,
            'total_time': total_time,
        })

    return merged


def generate_cheat_sheet(result, params, course_name="Course"):
    segments = result['segments']
    zones = _group_zones(segments)
    total_km = sum(s['distance_m'] for s in segments) / 1000

    zone_colors = {'climb': '#e74c3c', 'descent': '#3498db', 'flat': '#2ecc71'}

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{course_name} — Pacing Plan</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 20px auto; padding: 0 20px; color: #2c3e50; font-size: 12px; }}
  h1 {{ font-size: 20px; margin-bottom: 4px; }}
  .meta {{ color: #7f8c8d; margin-bottom: 16px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 12px 0; }}
  th {{ background: #34495e; color: white; padding: 6px 8px; text-align: left; font-size: 11px; }}
  td {{ padding: 5px 8px; border-bottom: 1px solid #ecf0f1; font-size: 11px; }}
  .stats {{ display: flex; gap: 20px; background: #f8f9fa; padding: 10px 16px; border-radius: 6px; margin: 12px 0; flex-wrap: wrap; }}
  .stat {{ text-align: center; }}
  .stat-val {{ font-size: 18px; font-weight: bold; }}
  .stat-label {{ font-size: 10px; color: #7f8c8d; }}
  .zone-climb {{ color: #e74c3c; font-weight: bold; }}
  .zone-descent {{ color: #3498db; font-weight: bold; }}
  .zone-flat {{ color: #2ecc71; font-weight: bold; }}
  .footer {{ margin-top: 20px; text-align: center; color: #bdc3c7; font-size: 10px; }}
  .params {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 4px 20px; margin: 8px 0; font-size: 11px; }}
  @media print {{ body {{ margin: 0; }} }}
</style>
</head>
<body>
<h1>{course_name}</h1>
<div class="meta">Generated by CyclingPacer | {total_km:.1f} km</div>

<div class="params">
  <span><b>Rider:</b> {params['rider']['mass_kg']:.0f} kg total</span>
  <span><b>FTP:</b> {params['ftp_w']:.0f} W</span>
  <span><b>Target ER:</b> {params['target_if']:.2f}</span>
  <span><b>CdA:</b> {params['rider']['cda']:.3f} m²</span>
  <span><b>Wind:</b> {abs(params['env']['wind_ms'])*3.6:.0f} km/h</span>
  <span><b>Temp:</b> {params.get('temperature_c', 20):.0f}°C</span>
</div>

<div class="stats">
  <div class="stat"><div class="stat-val">{_fmt_time(result['total_time_s'])}</div><div class="stat-label">Total Time</div></div>
  <div class="stat"><div class="stat-val">{result['wap_w']:.0f}W</div><div class="stat-label">WAP</div></div>
  <div class="stat"><div class="stat-val">{result['intensity_factor']:.2f}</div><div class="stat-label">Effort Ratio</div></div>
  <div class="stat"><div class="stat-val">{result['tss']:.0f}</div><div class="stat-label">Training Load</div></div>
  <div class="stat"><div class="stat-val">{result['variability_index']:.2f}</div><div class="stat-label">Variability</div></div>
</div>

<table>
<tr><th>Zone</th><th>From</th><th>To</th><th>Dist</th><th>Avg Grade</th><th>Power</th><th>Speed</th><th>Time</th></tr>
"""

    for z in zones:
        zone_cls = f"zone-{z['zone']}"
        html += f"""<tr>
  <td class="{zone_cls}">{z['zone'].title()}</td>
  <td>{z['start_km']:.1f} km</td>
  <td>{z['end_km']:.1f} km</td>
  <td>{z['distance_km']:.1f} km</td>
  <td>{z['avg_gradient']*100:.1f}%</td>
  <td><b>{z['avg_power']:.0f} W</b></td>
  <td>{z['avg_speed_kmh']:.1f} km/h</td>
  <td>{_fmt_time(z['total_time'])}</td>
</tr>
"""

    html += """</table>
<div class="footer">Generated by CyclingPacer (open source)</div>
</body>
</html>"""

    return html


def open_cheat_sheet(result, params, course_name="Course"):
    html = generate_cheat_sheet(result, params, course_name)
    with tempfile.NamedTemporaryFile('w', suffix='.html', delete=False) as f:
        f.write(html)
        path = f.name
    webbrowser.open('file://' + os.path.abspath(path))
    return path
